name: Release
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Parse Event
      id: event
      run: |
        echo "::set-output name=tag::$(jq -r '.release.tag_name' "${GITHUB_EVENT_PATH}" | sed s/^v//)"
    - name: Build golang build
      id: build
      run: |
        VERSION=${{ steps.event.outputs.tag }} ./build.sh

        echo "::set-output name=artifact::alfred-npmjs-${{ steps.event.outputs.tag }}.alfredworkflow"
    - name: Upload to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${{ steps.build.outputs.artifact }}
        asset_name: ${{ steps.build.outputs.artifact }}
        asset_content_type: application/zip
